name: cloudsre-hello-world-app-infra-deploy-play
on:
 push:
   tags:
     - CLOUDSRE-HELLO-WORLD-PLAY-INFRA-*
   paths:
     - "services/cloudsre-hello-world-app/infra-deploy/*.tf"
     - "!services/cloudsre-hello-world-app/infra-deploy/functionbeat.conf"

jobs:
  cloudsre-hello-world-app-infra-play-deployment:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Get the latest terraform version
        run: make terraform-install

      - name: Apply terraform cloudsre-hello-world-app infra
        run: |
          export APP_TAG=`echo $(git rev-parse HEAD) | cut -c1-7` && sed -i -e "s/APP_TAG/$APP_TAG/g" *.tf
          make terraform-apply
        working-directory: services/cloudsre-hello-world-app/infra-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: play
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PLAY_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PLAY_SECRET_KEY }}
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          DOCKER_GITHUB_TOKEN: ${{ secrets.DOCKERGITHUBTOKEN }}
          PRIVATE_REGISTRY_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}
          ENVIRONMENT: play
