name: student-api-infra-deploy
on:
 push:
   branches:
     - master
   tags:
     - STUDENT-API-PLAY-INFRA-*
   paths:
     - "student_service/infra-deploy/**"

jobs:
  student-api-infra-play-deployment:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Install botocore and boto3
        run: pip install botocore boto3

      - name: Get the latest terraform version
        run: make terraform-install

      - name: Apply terraform student infra
        run: make terraform-apply
        working-directory: services/student_service/infra-deploy/
        env:
          TF_IN_AUTOMATION           : true
          TF_WORKSPACE               : play
          AWS_ACCESS_KEY_ID          : ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY      : ${{ secrets.AWS_SECRET_KEY }}
          TF_CLOUD_TOKEN             : ${{ secrets.TF_CLOUD_TOKEN }}
          ANSIBLE_VAULT_PASSWORD_FILE: vault_env
          ANSIBLE_VAULT_PASSWORD     : ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          ENVIRONMENT: play
